version: "3"
services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: blogs-nginx
    depends_on:
      - api
      - mongo
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
  mongo:
    image: mongo:6.0.13
    restart: unless-stopped
    container_name: blogs-mongo
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
  api:
    build:
      context: api/
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/app/src
      - ./api/test:/app/test
      - ./api/package.json:/app/package.json
    container_name: blogs-api
    command: yarn run start:dev
    restart: unless-stopped
    environment:
      AUTH_LOGIN: admin
      AUTH_PASSWORD: qwerty
      MONGO_URL: mongodb://blogs-mongo:27017
      MONGO_DB_NAME: blogs
      JWT_SECRET: 123
volumes:
  dbdata6: {}
